#!/usr/bin/env bash

# Autostart
# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &
bsp-layout set tall &
pkill picom &
# picom &
picom --experimental-backends &
# polybar &

# Set Theme
bash ~/.config/bspwm/set-Theme.sh &

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 &

# Window Information
bspc config border_width 2 &
bspc config window_gap 12 &

bspc config split_ratio 0.5 &
bspc config borderless_monocle true &
bspc config gapless_monocle true &

bspc config pointer_follows_monitor true &
bspc config focus_follows_pointer true &

# $HOME/.fehbg &
# Rules
bspc rule -a Vlc state=floating follow=on &

sleep 2
polybar
